name: Build Docker Image

on:
  push:
    branches:
      - 'arm64'
    paths:
      - 'R-4.3-x86_64/*'
      - 'toolchain/*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build osxcross toolchain
        uses: docker/build-push-action@v3
        with:
          context: toolchain
          push: false
          tags: |
            ghcr.io/${{github.repository}}:toolchain

      - name: Build R-4.3-x86_64
        uses: docker/build-push-action@v3
        with:
          context: R-4.3-x86_64
          push: false
          tags: |
            ghcr.io/${{github.repository}}/r-4.3-x86_64:latest
            ghcr.io/${{github.repository}}:latest
